### ISSUE TITLE
Prevent duplicate posts

### ISSUE THREAD

**Issue by Camtendo** [Camtendo/ez-vs-streamer#4]
Let's determine a way to not post duplicates in the chat if the names are the same as last time. Could just disable the button after clicking it with a set of names and enable the button when input changes.

**Comment by bclymer** [comment]
Maybe just disable if it's within 5 minutes of the previous post. I can see 2 people playing twice in a row but different days in an odd scenario. I can't imaging somebody accidentally posting it twice beyond a 5 minute window.

**Comment by jjstobbe** [comment]
What if they mess up their name and repost? That's the only reason I could imagine them posting twice in under 5 minutes. (Or having the game end in under 5 minutes lmao)

**Comment by Camtendo** [comment]
It might be as simple as disable the button for a very small amount of time (3-5 seconds) after a submission happens, then any other submission could be assumed to be intentional? That'd cover all of the cases mentioned.
